playerSprite = new Image()
playerSprite.src = "assets/player.png"
iceSprite = new Image()
iceSprite.src = "assets/ice.png"
waterSprite = new Image()
waterSprite.src = "assets/water.png"
wallSprite = new Image()
wallSprite.src = "assets/wall.png"
goalSprite = new Image()
goalSprite.src = "assets/goal.png"
blankSprite = new Image()
blankSprite.src = "assets/blank.png"
hardIceSprite = new Image()
hardIceSprite.src = "assets/hard.png"
keySprite = new Image()
keySprite.src = "assets/key.png"

titleSprite = new Image()
titleSprite.src = "assets/title.png"
puffleSprite = new Image()
puffleSprite.src = "assets/puffle_on_ice.png"

levels = {
  "0": [
    "BBBBBBBBBBBBBBBBBBB",
    "BPIIIIIIIIIIIIIIIIB",
    "BIIIIIIIIIIIIIIIIIB",
    "BIIIIIIIIIIIIIIIIIB",
    "BIIIIIIIIIIIIIIIIIB",
    "BIIIIIIIIIIIIIIIIIB",
    "BIIIIIIIIIIIIIIIIIB",
    "BIIIIIIIIIIIIIIIIIB",
    "BIIIIIIIIIIIIIIIIIB",
    "BIIIIIIIIIIIIIIIIIB",
    "BIIIIIIIIIIIIIIIIIB",
    "BIIIIIIIIIIIIIIIIIB",
    "BIIIIIIIIIIIIIIIIIB",
    "BIIIIIIIIIIIIIIIIIB",
    "BBBBBBBBBBBBBBBBBBB"
  ],
  "1": [
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XBBBBBBBBBBBBBBBXXX",
    "XBGIIIIIIIIIIIPBXXX",
    "XBBBBBBBBBBBBBBBXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX"
  ],
  "2": [
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXBBBXXX",
    "XXXXXBBBBBBBXBGBXXX",
    "XXXXXBIIIIIBXBIBXXX",
    "XBBBBBIBBBIBBBIBXXX",
    "XBPIIIIBXBIIIIIBXXX",
    "XBBBBBBBXBBBBBBBXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX"
  ],
  "3": [
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXBBBXXXXXXXXBBBXXX",
    "XXBGBXXXXXXXXBPBXXX",
    "XXBIBXXXXBBBBBIBXXX",
    "XXBIBBBBBBIIBBIBXXX",
    "XXBIIIIIIIIIIIIBXXX",
    "XXBIIBBIIBBBBIIBXXX",
    "XXBBBBBBBBXXBBBBXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX"
  ],
  "4": [
    "XXXXXXXXXXXXXXXXXXX",
    "XBBBBBXXXXXXBBBBBXX",
    "XBIIIBBBBBBBBIIIBXX",
    "XBIBIBBIIIIBBIBIBXX",
    "XBIIIIIIIIIIIIIIBXX",
    "XBBIBBBBIIBBBBIBBXX",
    "XXBIBXBIIIIBXBIBXXX",
    "XXBPBXBIIIIBXBGBXXX",
    "XXBBBXBBBBBBXBBBXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX"
  ],
  "5": [
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXBBBXXX",
    "XXXXXXXXXXXXXBPBXXX",
    "XXXXBBBBBBBBBBIBBBX",
    "XBBBBIIIIIIIIIIIIBX",
    "XBGIIIIIIIIIIIIIIBX",
    "XBBBIIIIIIIIIIIIIBX",
    "XXXBBBBBBBBBBBBBBBX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX"
  ],
  "6": [
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXBBBXXX",
    "XXXXXXBBBBBXXBGBXXX",
    "XXXBBBBIIIBBBBIBBBX",
    "XBBBIIIIIIIIIBIIIBX",
    "XBPIIIIIIIIIIBIIIBX",
    "XBBBBIIIBIIIIIIIIBX",
    "XXXXBBBBBBBBBBBBBBX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX"
  ],
  "7": [
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XBBBBBBBBBBBBBBBXXX",
    "XBIIIIIIIIIIIIIBXXX",
    "XBIBBBBBBBBBBBIBBBB",
    "XBIBBBGIIIIIIIHIIIB",
    "XBIBBBBBBBBBBBIBBIB",
    "XBIBBBBBBBBBBBPBBIB",
    "XBIBBBBBBBBBBBBBBIB",
    "XBIBBBBIIBBIIIIBBIB",
    "XBIIIIIIIIIIIIIIIIB",
    "XBBBBBIIIIIIBBBBBBB",
    "XXXXXBBBBBBBBXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX"
  ],
  "8": [
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "BBBBBXXXBBBBBXXXXXX",
    "BIIIBBBBBIIIBXXXXXX",
    "BIBIBBPBBIBIBXXXXXX",
    "BIIHIIHIIHIIBBBBXXX",
    "BBBIBBIBBIBBBBGBXXX",
    "XBBIBBIBBIBBBBIBBXX",
    "XBIIIIHIIHIIBBIIBXX",
    "XBIIIBIBBIBIBIIIBXX",
    "XBIIIIIBBIIIBIBBBXX",
    "XBIBBBBBBBBBBIIIBXX",
    "XBIIIIIIIIIIIIIIBXX",
    "XBBBBBBBBBBBBBBBBXX"
  ],
  "9": [
    "XXBBBBBBBBBBBBBBBBX",
    "XBBIIIIIIIIIIIIIIBX",
    "XBIIBBBBHHIIIIHIIBX",
    "XBIIIHIIIIIIIIHIIBX",
    "XBBBIHBBBIBBBBIBBBX",
    "XXXBIHBBBGBIIBIBXXX",
    "XBBBIHBBBBBIIBIBXXX",
    "XBIIIIIBBBBIIBPBXXX",
    "XBIBBBIIIIIIIBBBXXX",
    "XBIBBBIIIIIBIBXXXXX",
    "XBIIIIIBBBIIIBXXXXX",
    "XBBBBBBBXBBBBBXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX"
  ]
  // "10": [
  //   "BBBBBBBBBBBBBBBBBBB",
  //   "BKIIIIIIIIIIIIIIIIB",
  //   "BIIIHHHHHHHHIIIIHIB",
  //   "BIIIIIIIIIIIIIIIHIB",
  //   "BIIIIIIBBBBBBIIIHIB",
  //   "BIIIIIIBBPBBHHIIHIB",
  //   "BIIIIIIBBIBBHHIIIIB",
  //   "BIIIIIIIIIIIIIIIIIB",
  //   "BIIIIIIIIIIIIIIIIIB",
  //   "BIIIIIIBBBIIIIBBBIB",
  //   "BIIIIIIIIIHHHHIIBIB",
  //   "BIIBBIIBBBIIIIBGBIB",
  //   "BIIBBHHIIBIIIIBBBIB",
  //   "BIIIIIIIIIIIIIIIIIB",
  //   "BBBBBBBBBBBBBBBBBBB"
  // ]
}
