frameCount = 0
frame = 1

playerSprite = new Image()
playerSprite.src = "assets/player.png"
iceSprite = new Image()
iceSprite.src = "assets/ice.png"
waterSprite = new Image()
waterSprite.src = "assets/water.png"
wallSprite = new Image()
wallSprite.src = "assets/wall.png"
goalSprite = new Image()
goalSprite.src = "assets/goal.png"
blankSprite = new Image()
blankSprite.src = "assets/blank.png"

levels = {
  "0": [
    "BBBBBBBBBBBBBBBBBBB",
    "BIIIIIIIIIIIIIIIIIB",
    "BIBIBIIBBBIIBIBIIIB",
    "BIIBIIIBIBIIBIBIIIB",
    "BIIBIIIBIBIIBIBIIIB",
    "BIIBIIIBBBIIBBBIIIB",
    "BIIIIIIIIIIIIIIIIIB",
    "BIIIIIIIIIIIIIIIIIB",
    "BIIIIIIIIIIIIIIIIIB",
    "BIIIIIIIIIIIIIIIIIB",
    "BIIIIIIIIIIIIIIIIIB",
    "BIIIIIIIIIIIIIIIIIB",
    "BIIIIIIIIIIIIIIIIIB",
    "BIIIIIIIIIIIIIIIIIB",
    "BBBBBBBBBBBBBBBBBBB"
  ],
  "1": [
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XBBBBBBBBBBBBBBBXXX",
    "XBGIIIIIIIIIIIPBXXX",
    "XBBBBBBBBBBBBBBBXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXX"
  ],
  "2": [
    "XXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXBBBXXXX",
    "XXXXXBBBBBBBXBGBXXXX",
    "XXXXXBIIIIIBXBIBXXXX",
    "XBBBBBIBBBIBBBIBXXXX",
    "XBPIIIIBXBIIIIIBXXXXX",
    "XBBBBBBBXBBBBBBBXXXX",
    "XXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXX"
  ],
  "3": [
    "XXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXX",
    "XXBBBXXXXXXXXBBBXXXX",
    "XXBGBXXXXXXXXBPBXXXX",
    "XXBIBXXXXBBBBBIBXXXX",
    "XXBIBBBBBBIIBBIBXXXX",
    "XXBIIIIIIIIIIIIBXXXX",
    "XXBIIBBIIBBBBIIBXXXX",
    "XXBBBBBBBBXXBBBBXXXX",
    "XXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXX"
  ],
  "4": [
    "XXXXXXXXXXXXXXXXXXXX",
    "XBBBBBXXXXXXBBBBBXXX",
    "XBIIIBBBBBBBBIIIBXXXX",
    "XBIBIBBIIIIBBIBIBXXX",
    "XBIIIIIIIIIIIIIIBXXX",
    "XBBIBBBBIIBBBBIBBXXX",
    "XXBIBXBIIIIBXBIBXXXX",
    "XXBPBXBIIIIBXBGBXXXX",
    "XXBBBXBBBBBBXBBBXXXX",
    "XXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXX"
  ],
  "5": [
    "XXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXBBBXXXX",
    "XXXXXXXXXXXXXBPBXXXX",
    "XXXXBBBBBBBBBBIBBBXX",
    "XBBBBIIIIIIIIIIIIBXX",
    "XBGIIIIIIIIIIIIIIBXX",
    "XBBBIIIIIIIIIIIIIBXX",
    "XXXBBBBBBBBBBBBBBBXX",
    "XXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXX"
  ],
  "6": [
    "XXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXIIIXXXXGXXXXX",
    "XXXXIIIIIIIIIXIIIXXX",
    "XXPIIIIIIIIIIXIIIXXX",
    "XXXXXIIIXIIIIIIIIXXX",
    "XXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXX"
  ]
}
